server:
  port: 8000
  debug: false
  environment: "local, production"
  domain: "your domain"
psql:
  host: "..."
  user: "..."
  database: "..."
  port: 5432
  password: "..."
  pool-min-size: 10
  pool-max-size: 20
cloudflare-turnstile:
  secret-key: "your cloudflare turnstile secret key"
jwt:
  secret: "your jwt secret" # python -c "import secrets; print(secrets.token_hex(64))"
s3:
  base-url: "..." # public access url where public can access your items
  endpoint: "..." # endpoint for requests
  bucket-name: "..."
  access-key-id: "..."
  secret-access-key: "..."
  location: "auto" # note: auto is for R2 cloudflare only.